//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elyon.Fastly.EmailJob.DomainServices.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Elyon.Fastly.EmailJob.DomainServices.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _01_Schulungspräsentation_compressed {
            get {
                object obj = ResourceManager.GetObject("_01_Schulungspräsentation_compressed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _02_Informationsflyer_compressed {
            get {
                object obj = ResourceManager.GetObject("_02_Informationsflyer_compressed", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _03_Offizielles_Informationsschreiben_des_Kanton_Baselland {
            get {
                object obj = ResourceManager.GetObject("_03_Offizielles_Informationsschreiben_des_Kanton_Baselland", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _04_Vereinbarung_zwischen_Kanton_und_Betrieb {
            get {
                object obj = ResourceManager.GetObject("_04_Vereinbarung_zwischen_Kanton_und_Betrieb", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _05_Einverständniserklärung_für_den_Teilnehmenden__Erwachsene_ {
            get {
                object obj = ResourceManager.GetObject("_05_Einverständniserklärung_für_den_Teilnehmenden__Erwachsene_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _05_Einverständniserklärung_für_den_Teilnehmenden__Minderjährige_ {
            get {
                object obj = ResourceManager.GetObject("_05_Einverständniserklärung_für_den_Teilnehmenden__Minderjährige_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _06_Anmeldeformular_Depooling_für_die_Teilnehmenden__Erwachsene_ {
            get {
                object obj = ResourceManager.GetObject("_06_Anmeldeformular_Depooling_für_die_Teilnehmenden__Erwachsene_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _06_Anmeldeformular_Depooling_für_die_Teilnehmenden__Minderjährige_ {
            get {
                object obj = ResourceManager.GetObject("_06_Anmeldeformular_Depooling_für_die_Teilnehmenden__Minderjährige_", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _07_Anfahrtsplan_Labor_Muttenz {
            get {
                object obj = ResourceManager.GetObject("_07_Anfahrtsplan_Labor_Muttenz", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Handbuch_BTBL_BBL_KMU {
            get {
                object obj = ResourceManager.GetObject("Handbuch_BTBL_BBL_KMU", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
